---
# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: community
name: rhel_ops
version: 0.1.0
readme: README.md
authors:
  - Yanis Guenane <yguenane@redhat.com>
  - Craig Brandt <craig.brandt1@gmail.com>
  - Justin Cinkelj <justin.cinkelj@xlab.si>
description: null
license_file: LICENSE
tags:
# tags so people can search for collections https://galaxy.ansible.com/search
# tags are all lower-case, no spaces, no dashes.
  - rhel
  - operations
repository: https://github.com/ansible-collections/community.rhel_ops
#documentation: https://github.com/ansible-collection-migration/community.rhel_ops/tree/main/docs
homepage: https://github.com/ansible-collections/community.rhel_ops
issues: https://github.com/ansible-collections/community.rhel_ops/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
